language: java

jdk:
  - openjdk8

env:
  global:
    - PATH="$PATH:/usr/lib/dart/bin"

before_install:
  - chmod +x ./gradlew
  - chmod +x ./config/scripts/publish-artifacts.sh
  - chmod +x ./config/scripts/update-apt.sh
  - ./config/scripts/update-apt.sh
  - sudo apt-get install dart
  - flutter pub global activate protoc_plugin
  - flutter pub global activate dart_code_gen

script:
  - ./gradlew check --stacktrace

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
