language: java

before_install:
  - chmod +x gradlew

install:
  - openssl aes-256-cbc -K $encrypted_484d6a99d515_key -iv $encrypted_484d6a99d515_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

script:
  - ./gradlew check --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x ./config/scripts/report-coverage.sh
  - ./config/scripts/report-coverage.sh
