language: java

jdk:
  - openjdk8

env:
  global:
    - PATH="$PATH:/usr/lib/dart/bin"

before_install:
  - chmod +x ./gradlew
  - chmod +x ./config/scripts/publish-artifacts.sh
  - chmod +x ./script/install-dart.sh
  - ./script/install-dart.sh
  - pub global activate protoc_plugin
  - pub global activate dart_code_gen

install:
  - openssl aes-256-cbc -K $encrypted_484d6a99d515_key -iv $encrypted_484d6a99d515_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

script:
  - ./gradlew check --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - ./config/scripts/publish-artifacts.sh


after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
