name: Build under Ubuntu

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: Pull config
        run: git submodule update --init --recursive

      - name: Install Dart SDK
        shell: bash
        run: |
          chmod +x ./config/scripts/update-apt.sh
          ./config/scripts/update-apt.sh
          sudo apt-get install dart
          echo "/usr/lib/dart/bin" >> $GITHUB_PATH
          echo "Updated PATH:"
          echo "$PATH"

      - name: Activate Dart protoc plugin
        shell: bash
        run: |
          pub global activate protoc_plugin
          pub global activate dart_code_gen

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build --stacktrace

      - name: Upload code coverage report
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
